---
title: Tangm1.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: "//mingtang.me"
harmony:
  name: Ming Tang - Personal Website
  description: Understanding Earth Through Chemistry
  meta_description: Ming Tang - Understanding Earth Through Chemistry | Rice University,
    Department of Earth Science
  basetheme: theme-base-01
  google_analytics_key: UA-92899048-1
  social:
    github: 
    twitter: 
    facebook: 
    gplus: 
    dribble: 
    pinterest: 
    solidlogo: false
  show_disclaimer: false
markdown: kramdown
highlighter: rouge
permalink: pretty
gems:
- jekyll-tidy
exclude:
- CNAME
- Gemfile
- Rakefile
- README.md
- ".gitignore"
- ".sass-cache"
- Gemfile.lock
- vendor
sass:
  sass_dir: assets/css/_sass
  style: :compressed
