# Harmony Jekyll theme general configurations

# Base URL
# baseurl: /harmony

# Site live URL
url: //mingtang.me

# Localhost
# url: http://127.0.0.1:4000

# Harmony theme configuration. Please change accordingly.
harmony:
  name: Ming Tang
  # Little description about your site
  description: I am a Geochemist-To-Be!
  # 'meta_description:' Write an awesome description for your new site here.
  # It will appear in your document head meta (for Google search results) and
  # in your feed.xml site description.
  meta_description: > #
   Ming Tang - Rice University, Department of Earth Science
  basetheme: theme-base-01 # pre defined thmes are darken, blue-water, redish.
  # author: # Author details
  #   name: Gayan Virajith
  #   email: gayanvirajith@gmail.com
  #   url: http://gayanvirajith.github.io

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-92899048-1

  # Profile links, leave blank to ignore
  social:
    github:
    twitter:
    facebook:
    gplus:
    dribble:
    pinterest:
    solidlogo: true
  # Toggle disclaimer in footer
  show_disclaimer: false

# Conversion / Build settings
markdown:    kramdown
# This is how you put pygments config in jekyll 2.0 instead of pygments: true
highlighter: rouge

# Permalinks
permalink:        pretty

exclude:
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock
  - vendor

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed
